/*
 * Programa para apresentação de fractais usando JFrame
 */
package com.blogspot.h3dema;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JColorChooser;
import javax.swing.Timer;

/**
 * Usamos o fractal apresentado em "Java como programar"
 *
 * @author Henrique
 */
public class FractalLo extends javax.swing.JFrame {

    JPanelFractal areaDesenho;
    Timer tm;

   /**
     * Creates new form FractalLo
     */
    public FractalLo() {
        initComponents();
        areaDesenho = new JPanelFractal(JPanelFractal.MIN_NIVEL);
        lblDisplayNivel.setText(String.format("Nível: %02d", areaDesenho.getNivel()));
        areaDesenho.setMinimumSize(new Dimension(400, this.getMinimumSize().width));
        getContentPane().add(areaDesenho, java.awt.BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnAlterarCor = new javax.swing.JButton();
        btnAumentarNivel = new javax.swing.JButton();
        btnDiminuirNivel = new javax.swing.JButton();
        lblDisplayNivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desenho de Fractal de Sin Han Lo");
        setMinimumSize(new java.awt.Dimension(216, 400));
        setName("janelaPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        painelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnAlterarCor.setText("Alterar cor");
        btnAlterarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCorActionPerformed(evt);
            }
        });
        painelBotoes.add(btnAlterarCor);

        btnAumentarNivel.setText("+");
        btnAumentarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarNivelActionPerformed(evt);
            }
        });
        painelBotoes.add(btnAumentarNivel);

        btnDiminuirNivel.setText("-");
        btnDiminuirNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirNivelActionPerformed(evt);
            }
        });
        painelBotoes.add(btnDiminuirNivel);

        lblDisplayNivel.setText("Nivel: ");
        painelBotoes.add(lblDisplayNivel);

        getContentPane().add(painelBotoes, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCorActionPerformed
        // trocar a cor utilizada no desenho
        Color corSelecionada = JColorChooser.showDialog(this, "Escolha uma cor", areaDesenho.getCor());
        if (null != corSelecionada) {
            areaDesenho.setCor(corSelecionada);
            repaint();
        }

    }//GEN-LAST:event_btnAlterarCorActionPerformed

    private void ajustaNivelDesenho(int nivel) {
        areaDesenho.setNivel(nivel);
        if (nivel == areaDesenho.getNivel()) {
            lblDisplayNivel.setText(String.format("Nível: %02d", nivel));
            repaint();
        } else {
            lblDisplayNivel.setText(String.format("Nível: %02d - limite atingido", areaDesenho.getNivel()));
        }    
    }
    
    private void btnDiminuirNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirNivelActionPerformed
        // diminui o nível do fractal
        ajustaNivelDesenho(areaDesenho.getNivel() - 1);

    }//GEN-LAST:event_btnDiminuirNivelActionPerformed

    private void btnAumentarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarNivelActionPerformed
        // aumentar o nível do fractal
        ajustaNivelDesenho(areaDesenho.getNivel() + 1);
    }//GEN-LAST:event_btnAumentarNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractalLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractalLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractalLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractalLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractalLo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCor;
    private javax.swing.JButton btnAumentarNivel;
    private javax.swing.JButton btnDiminuirNivel;
    private javax.swing.JLabel lblDisplayNivel;
    private javax.swing.JPanel painelBotoes;
    // End of variables declaration//GEN-END:variables
}
